CREATE TABLE INTEGRANTE (
id_integrante INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
dni INT UNIQUE,
nombre VARCHAR(20),
apellido VARCHAR(20) NOT NULL,
email VARCHAR(50) UNIQUE NOT NULL,
recomendacion TINYTEXT
);

CREATE TABLE ESTUDIANTE (
id_integrante INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
db_relacional BOOLEAN NOT NULL,
db_no_relacional BOOLEAN NOT NULL,
FOREIGN KEY (id_integrante) REFERENCES INTEGRANTE (id_integrante) 
);

CREATE TABLE DOCENTE (
id_integrante INT PRIMARY KEY NOT NULL AUTO_INCREMENT, 
FOREIGN KEY (id_integrante) references INTEGRANTE (id_integrante) 
);

CREATE TABLE MATERIA (
id_materia INT PRIMARY KEY NOT NULL AUTO_INCREMENT, 
codigo VARCHAR(20) UNIQUE,
nombre VARCHAR(50) NOT NULL
);

CREATE TABLE ROL (
id_rol INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
nombre VARCHAR(50) NOT NULL,
descripcion TINYTEXT
);

CREATE TABLE GRUPO (
id_grupo INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
nombre VARCHAR(100) NOT NULL
);

CREATE TABLE MASCOTA (
id_mascota INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
tipo VARCHAR(20) NOT NULL UNIQUE
);

CREATE TABLE LOCALIDAD (
id_localidad INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
nombre VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE HOBBY (
id_hobby INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
nombre VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE TRABAJO (
id_trabajo INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
nombre VARCHAR(100) NOT NULL UNIQUE
);

